movies/API/urls.py
from django.conf.urls import url

from .views import MovieDetailAPIView, MovieListAPIView

app_name = 'API'

urlpatterns = [
    url(r'^$', MovieListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MovieDetailAPIView.as_view(), name='detail')
]

movies/core/urls.py
from django.conf.urls import url

from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^top5/$', views.Top5View.as_view(), name='top5'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^movie/add/$', views.MovieCreate.as_view(), name="movie-add"),
    url(r'^movie/(?P<pk>[0-9]+)/$', views.MovieUpdate.as_view(), name="movie-update"),
    url(r'^movie/(?P<pk>[0-9]+)/delete/$', views.MovieDelete.as_view(), name="movie-delete")
]

movies/movies/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('core.urls')),
    url(r'^api/', include('API.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models


class Movie(models.Model):
    """
    Describes a movie with properties such as title, production_company, etc.
    """
    position = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=1024)
    production_company = models.CharField(max_length=1024, blank=True)
    rating = models.IntegerField(blank=True, null=True)
    movie_url = models.CharField(max_length=1024, blank=True)
    image_url = models.CharField(max_length=1024, blank=True)

    def get_absolute_url(self):
        return reverse('core:detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.title

movies/API/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from core.models import Movie

from .serializers import MovieSerializer


class MovieListAPIView(ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class MovieDetailAPIView(RetrieveAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

movies/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Movie


class IndexView(ListView):
    template_name = "core/index.html"
    context_object_name = 'all_movies'

    def get_queryset(self):
        return Movie.objects.all()


class Top5View(ListView):
    template_name = "core/top5.html"
    context_object_name = 'all_movies'

    def get_queryset(self):
        return Movie.objects.all()


class DetailView(DetailView):
    model = Movie
    template_name = "core/detail.html"


class MovieCreate(CreateView):
    model = Movie
    fields = [
        'position', 'title', 'production_company',
        'rating', 'movie_url', 'image_url'
    ]


class MovieUpdate(UpdateView):
    model = Movie
    fields = [
        'position', 'title', 'production_company',
        'rating', 'movie_url', 'image_url'
    ]


class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('core:index')

movies/core/templates/core/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Movies{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Navbar -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'core:index' %} ">Movies app</a>
        </div>

        <!-- Items in Navbar -->
        <div class ="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'core:top5' %}">
                        <span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp;Top5
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'core:movie-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Movie
                    </a>
                </li>
            </ul>

        </div>
        
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movies/core/templates/core/detail.html
{% extends 'core/base.html' %}
{% block title %}{{ movie.title }}{% endblock %}
{% load staticfiles %}

{% block body %}

<div class="col-sm-4 col-lg-2">
    <div class="thumbnail">

        <img src="{{ movie.image_url }}">

    </div>
</div>
    
        <h2>Movie Title: {{ movie.title }}</h2>
        <h4>Production Company:  {{ movie.production_company }}</h4>

        {% if movie.rating == None %}
            <h4>Average Rating: <img src="{% static 'core/images/wtsicon.png' %}"  style="height: 26px; width: 25px;"/>
            Not rated yet</h4>
        {% else %}
            <h4>Average Rating: <img src="{% static 'core/images/tomato.png' %}"  style="height: 26px; width: 25px;"/>
            {{ movie.rating }} %</h4>
        {% endif %}

{% endblock %}

movies/core/templates/core/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

movies/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block body %}
{% load staticfiles %}

    {% if all_movies %}
        <h2><center>Movie list:</center></h2>

            <div class="col-md-4">
                <div class="panel panel-primary">

                    <div class="panel-heading">
                        <h4 class="panel-title">
                        Top 5 Movies
                        </h4>
                    </div>

                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            {% for movie in all_movies|slice:":5" %}

                                <p><a href="{% url 'core:detail' movie.id %}">
                                {{ movie.title }} </a>
 
                                {% if movie.rating == None %}

                                <img src="{% static 'core/images/wtsicon.png' %}"  style="height: 18px; width: 18px;"/>

                                {% else %}
                                <img alt="" src="{% static 'core/images/tomato.png' %}" style="height: 18px; width: 18px;" /> {{ movie.rating }} %
                                {% endif %}</p>
                                <p>{{ movie.production_company | truncatechars:50 }}</p>

                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>


            {% for movie in all_movies %}
            <div class="col-md-8 col-lg-2">
                <div class="thumbnail">
                    <div class="caption">
                        <a href="{% url 'core:detail' movie.id %}"><img src="{{ movie.image_url }}"></a>
                        <h5><a href="{% url 'core:detail' movie.id %}">{{ movie.title | truncatechars:25 }}</a></h5>

                        <form action="{% url 'core:movie-update' movie.id %}" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="movie_id" value="{{ transaction.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>

                        <form action="{% url 'core:movie-delete' movie.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                 <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                        {% if movie.rating == None %}

                        <img src="{% static 'core/images/wtsicon.png' %}"  style="height: 26px; width: 25px;"/>

                        {% else %}
                        <img alt="" src="{% static 'core/images/tomato.png' %}" style="height: 26px; width: 25px;" /> {{ movie.rating }} %
                        {% endif %}

                    </div>
                </div>
            </div>
            {% endfor %}



    {% else %}
        <h3>No movies in database</h3>
    {% endif %}



{% endblock %}

movies/core/templates/core/movie_form.html
{% extends 'core/base.html' %}

{% block body %}



    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'core/form-template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>










{% endblock %}

movies/core/templates/core/top5.html
{% extends 'core/base.html' %}
{% block title %} Top 5 {% endblock %}
{% load staticfiles %}

{% block body %}

            {% for movie in all_movies|slice:":5" %}
            <div class="">
                <div class="thumbnail">
                    <div class="caption">
                        <p><h4>Position: {{ movie.position }}</h4>
                        <h4>Movie Title: <a href="{% url 'core:detail' movie.id %}">{{ movie.title }}</a></h4>
                        <h4>Production company: {{ movie.production_company }}</h4>

                        {% if movie.rating == None %}
                        <h4>Average Rating: <img src="{% static 'core/images/wtsicon.png' %}"  style="height: 26px; width: 25px;"/>
                        Not rated yet.</h4>
                        {% else %}
                        <h4>Average Rating: <img alt="" src="{% static 'core/images/tomato.png' %}" style="height: 26px; width: 25px;" /> {{ movie.rating }} %</h4>
                        {% endif %}</p>

                        <p><img src="{{ movie.image_url }}"></p>

                        <form action="{% url 'core:movie-update' movie.id %}" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="movie_id" value="{{ transaction.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </form>

                        <form action="{% url 'core:movie-delete' movie.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                 <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                    </div>
                </div>
            </div>
            {% endfor %}

{% endblock %}